
name: Update Website Image

on:
  push:
    paths:
      - 'calendars/*'

jobs:
  update-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Update Image on Website
      run: |
        # find the target png file from the folder.
        IMAGE_PATH=$(find ./calendars -name 'calendar_*.png')
        
        #double check if there is one img file in the folder
        if [ $(echo $IMAGE_PATH | wc -w) -eq 1 ]; then
          echo "Uploading $IMAGE_PATH"

          #uploading img to the website
          curl -X POST -H "Authorization: Bearer ${{ secrets.WEBSITE_ACCESS_TOKEN }}" -F "image=@$IMAGE_PATH" https://example.com/api/upload
          
          #check status and log the result
          echo "Image uploaded successfully"
        else
          echo "Error: 0 or more than 1 images found in calendars directory."
        fi

        env:
        WEBSITE_ACCESS_TOKEN: ${{ secrets.WEBSITE_ACCESS_TOKEN }}
        
